migration to composition api (#37)
* chore(*): migration to composition api

update deps
update technical stack with https://github.com/electron-vite/electron-vite-vue
migration to composition api

* fix(*): click button

* fix(*): watch props

* proofread a comment

* run linter

* merge new code into window_config, use window_config

* revise variable names for consistency

* do some manual lint resolution

* revise method call to match new method name

* revise some comments for consistency

* fix "Maximum recursive updates exceeded"

* fix "log.transcript.trim is not a function"

* fix "Cannot find name '$emit'."

* fix data type mismatches

* fix "possibly 'null'"

* clean up some comments

* restore word replace

* remove duplicate and unused code

* fix some inconsistent formatting

* fix edit function

* revise some comments for consistency

* fix "Write operation failed: computed value is readonly"

* clean up some code

* restore value

* temporarily insert some debugging (revert this later)

* clean up some code

* fix web app failing to send messages to desktop app

window.ipcRenderer.receive('channel', (data) => { methodName(data) }) → window.ipcRenderer.on('message', (event, data) => { methodName(data) }) (See: electron\preload\index.ts)

* fix broadcast behavior on desktop app

* fix update check

* implement $reset() for stores, fix button "Reset all settings"

* clean up some code

* restore code, fix electron window config persistence

* Revert "temporarily insert some debugging"

This reverts commit d318543c0d46be1108ba2dc0a0ce349d5d193841.

* move some code

* route the user to '/' to apply theme on reset

* update resetStore() function

* remove unnecessary assign in resetStore()

* remove a fix that became unnecessary

* remove unused dep

* update dep, move pages settings

* v-for and router improvs

* chore(*): delete comment lines

* chore(text-field): add rules

* chore(*): formatting

* chore(*): rename interfaces

* chore(*): regroup plugins

* chore(footer): formatting

* chore(*): scoped css few sfc, and convert v-html

* chore(*) default language value

* chore(settings): move language into store

* fix(appearance): deep css

* chore(appareance): add key

* chore(*): fix refacto interface

* declare type

* update base router url

* properly import logo in welcome overlay

* remove console log

* add icon in electron builder config

* update requirements

* use @xenova/transformers in the Electron process to avoid error

addresses error: Uncaught Error: Dynamic require of "fs" is not supported

* try to fix some build errors

* fix build errors

* run lint:fix

* ipcrenderer only runs on electron

* fix issue where ignoring case on word replace would lowercase entire msg

* version 0.4.0

---------

Co-authored-by: Saya <117558001+fuwako@users.noreply.github.com>
Co-authored-by: nae <nae@risu.dev>